---
- name: FQCN transform should preserve blank lines between tasks
  hosts: localhost
  tasks:
    - name: Task1
      debug:
        msg: hello

    - name: Task2
      debug:
        msg: hello

    - name: Task3
      debug:
        msg: hello
