---
- name: Import a role
  ansible.builtin.import_role: local.testcollection.bug4095

- name: Import a role that is in a subdirectory
  ansible.builtin.import_playbook: local.testcollection.subdirectory.bug4452
