---
- name: One
  hosts: all
  tasks:
    - name: Test when with jinja2 # noqa: jinja[spacing]
      ansible.builtin.debug:
        msg: text
      when: "false"

- name: Two
  hosts: all
  roles:
    - role: hello
      when: "'1' = '1'"

- name: Three
  hosts: all
  roles:
    - role: hello
      when:
        - "'1' = '1'"

- name: Four
  hosts: all
  tasks:
    - name: Test when with jinja2 embedded in quoted string # noqa: jinja[spacing]
      ansible.builtin.debug:
        msg: text
      when: not "version={{ expected_version }}" in stdout

- name: Five
  hosts: all
  tasks:
    - name: Test when with a whole jinja2 block quoted # noqa: jinja[spacing]
      ansible.builtin.debug:
        msg: text
      when: "'{{ v }}' == '8'"
