---
- name: Role for 4452
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Import role in subdir
      ansible.builtin.import_role:
        name: local.testcollection.subdirectory.bug4452
