---
# Sync RTD redirects
name: redirects

"on":
  push:
    branches:
      - main
    paths:
      - docs/redirects.yml
      - .github/workflows/redirects.yml

  # Manually triggered using GitHub's UI
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs:
    environment: release
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.0
      - uses: actions/setup-python@11d48d784bee1c51dcf3fe1718cfab5191b50317 # v5.3.0

      - name: Upgrade Python toolchain
        run: python3 -m pip install --upgrade pip setuptools wheel

      - name: Install readthedocs-cli
        run: python3 -m pip install readthedocs-cli

      - name: Sync redirects
        run: rtd projects ansible-lint redirects sync -f docs/redirects.yml --wet-run
        env:
          RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
