---
name: security-check
"on":
  pull_request_target:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
jobs:
  security-check:
    uses: ansible/team-devtools/.github/workflows/security-check.yml@feat/pr-security-checks
    secrets: inherit
